services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=mydb
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}