spring:
  application:
    name: authorization
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/mydb
    username: admin
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      mode: always